### ISSUE TITLE
max_page - no information provided to the end user

### ISSUE THREAD

**Issue by ro-savage** [bsm/grape-pagy#11]
First -- thanks for the great plugin. Super easy to use.

Following on from #8 - there is no way for the user to know what the `max_items` is set to.

So if it defaults to `per_page=10` and the max is also `10` and a user puts in `per_page=20`. There isn't anyway they can know this was invalid.

Since no error is returned, I would suggest that the `max_page` value automatically be added to the description of per page.
 
Alternatively, there should be a way to overwrite the default description value.

**Comment by dim** [comment]
Sorry Ro, not strictly following, are you referring to the description message being made configurable, i.e. https://github.com/bsm/grape-pagy/blob/main/lib/grape/pagy.rb#L42? Would you mind submitting a PR for that?

**Comment by ro-savage** [comment]
Sorry for not making it clear.

Given this code, which sets max_items to `500`

```ruby
          use :pagy, items_param: :per_page, items: 500, max_items: 500
```

The documentation generated doesn't show what the max_items is
<img width="571" alt="image" src="https://user-images.githubusercontent.com/9244507/180165092-cf897e48-1332-4d7b-b397-40665639642f.png">

Therefore the person interacting with the API has no idea what the max value for `per_page` is.

My suggestion would be to either
1. Add the `max_items` to the default description. So in the above case it would read 
"Number of items to return per page. Maximum: 500"
2. Allow passing `desc` to overwrite the default descriptions
